Doanltweb/Controllers/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Doanltweb.Models;

namespace Doanltweb.Controllers
{
    public class NguoidungController : Controller
    {
        QLBanhangDataContext db = new QLBanhangDataContext();
        // GET: Nguoidung
        
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }

        //POST: Hàm Dangky(post) Nhận dữ liệu từ trang DangKy và thực hiện việc tạo mới dữ liệu
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, taiKhoanTV kh)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến
            var hodemkh = collection["HodemKH"];
            var tenkh = collection["TenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var nhaplaimatkhau = collection["Nhaplaimatkhau"];
            var email = collection["Diachi"];
            var diachi = collection["Email"];
            var sodienthoai = collection["Dienthoai"];
            
            if (string.IsNullOrEmpty(hodemkh))
            {
                ViewData["Loi1"] = " Họ đệm không được để trống";
            }
            else if (string.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = " Tên không được để trống";
            }
            else if (string.IsNullOrEmpty(tendn))
            {
                ViewData["Loi3"] = " Tên đăng nhập không được để trống";
            }
            else if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi4"] = " Mật khẩu không được để trống";
            }
            else if (string.IsNullOrEmpty(nhaplaimatkhau))
            {
                ViewData["Loi5"] = "Nhập lại mật khẩu";
            }
            if (string.IsNullOrEmpty(diachi))
            {
                ViewData["Loi6"] = "Địa chỉ không được để trống";
            }
            if (string.IsNullOrEmpty(sodienthoai))
            {
                ViewData["Loi7"] = "Số điện thoại không được để trống";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (kh)
                kh.hoDem = hodemkh;
                kh.tenTV = tenkh;
                kh.taiKhoan = tendn;
                kh.matKhau = matkhau;
                kh.email = email;
                kh.diaChi = diachi;
                kh.soDT = sodienthoai;
               
                db.taiKhoanTVs.InsertOnSubmit(kh);
                db.SubmitChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();

        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        //POST: Hàm Dangnhap(post) Nhận dữ liệu từ trang Dangnhap và thực hiện việc tạo mới dữ liệu
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            //Gán các giá trị người dùng nhập liệu cho các biến
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if (string.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được bỏ trống";
            }
            else if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Mật khẩu không được bỏ trống";
            }
            else
            {
                // Gán giá trị đối tượng được tạo mới(kh)
                taiKhoanTV kh = db.taiKhoanTVs.SingleOrDefault(n => n.taiKhoan == tendn && n.matKhau == matkhau);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Đăng nhập thành công";
                    Session["taiKhoan"] = kh;
                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

Doanltweb/Views/Nguoidung/Dangky.cshtml
@{
    ViewBag.Title = "Dangky";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Đăng ký thành viên</h5>
        </div>
        <div class="modal-body">
            <form action="#" method="post">
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        <label class="col-form-label">Họ đệm</label>
                        <input type="text" class="form-control" placeholder="Nhập họ đệm của bạn" name="HodemKH">
                        @ViewData["Loi1"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Tên</label>
                        <input type="text" class="form-control" placeholder="Nhập tên của bạn" name="TenKH">
                        @ViewData["Loi2"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Tên đăng nhập</label>
                        <input type="text" class="form-control" placeholder="Nhập tên đăng nhập" name="TenDN">
                        @ViewData["Loi3"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Mật khẩu</label>
                        <input type="password" class="form-control" placeholder="Nhập mật khẩu " name="Matkhau">
                        @ViewData["Loi4"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Nhập lại mật khẩu</label>
                        <input type="password" class="form-control" placeholder="Nhập lại mật khẩu " name="Nhaplaimatkhau">
                        @ViewData["Loi5"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Email</label>
                        <input type="email" class="form-control" placeholder="Nhập email" name="Email">

                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Số điện thoại</label>
                        <input type="text" class="form-control" placeholder="Nhập số điện thoại" name="SoDT">
                        @ViewData["Loi7"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Địa chỉ</label>
                        <input type="text" class="form-control" placeholder="Nhập địa chỉ" name="Diachi">
                        @ViewData["Loi6"]
                    </div>

                    <div class="right-w3l">
                        <input type="submit" class="form-control" value="Đăng Ký">
                    </div>
                }
            </form>
        </div>
    </div>
</div>

Doanltweb/Views/Nguoidung/Dangnhap.cshtml
        @{
            ViewBag.Title = "Dangnhap";
            Layout = "~/Views/Shared/_Layout.cshtml";
        }

<h4 style="color:red; text-align:center">@ViewBag.Thongbao</h4>
<div class="modal-dialog" role="document">
    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title text-center">Đăng nhập</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="#" method="post">
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        <label class="col-form-label">Tên đăng nhập</label>
                        <input type="text" class="form-control" name="TenDN" placeholder="Nhập tên đăng nhập">
                        @ViewData["Loi1"]
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Mật khẩu</label>
                        <input type="password" class="form-control" placeholder="Nhập mật khẩu " name="Matkhau">
                        @ViewData["Loi2"]
                    </div>
                    <div class="right-w3l">
                        <input type="submit" class="form-control" value="Đăng nhập">
                    </div>
                }
                <p class="text-center dont-do mt-3">
                    Nếu bạn chưa có tài khoản ?
                    @Html.ActionLink("Đăng ký tại đây", "Dangky", "Nguoidung")
                </p>
            </form>
        </div>
    </div>
</div>